# Generated by Django 5.0.6 on 2025-03-24 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_likes_user_alter_tag_slug'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_types',
            field=models.IntegerField(choices=[(1, 'Like'), (2, 'Comment'), (3, 'Follow')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_post', to='app.post'),
        ),
    ]
