# Generated by Django 5.0.6 on 2025-03-28 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reciepient',
            new_name='recipient',
        ),
    ]
