# Generated by Django 5.0.6 on 2025-04-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0003_message_unread_alter_message_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='unread',
        ),
    ]
